// front/src/components/ShowAll.vue
<template>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header">一覧</div>
          <div class="card-body">
            <table class="table">
              <tr>
                <th>ID</th>
                <th>名前</th>
                <th>メール</th>
                <th>メッセージ</th>
                <th></th>
                <th></th>
                <th></th>
              </tr>
              <tr v-for="(inquiry, key) in inquiries" :key="key">
                <td>{{ inquiry.id }}</td>
                <td>{{ inquiry.name }}</td>
                <td>{{ inquiry.mail }}</td>
                <td>{{ inquiry.message }}</td>
                <td>
                  <router-link :to="/detail/ + inquiry.id" class="btn btn-primary" role="button">詳細</router-link>
                </td>
                <td>
                  <router-link :to="/edit/ + inquiry.id" class="btn btn-secondary" role="button">編集</router-link>
                </td>
                <td><button class="btn btn-danger" @click.prevent="deleteById(inquiry.id)">削除</button></td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import axios from 'axios'

export default {
  name: 'ShowAll',
  data () {
    return {
      inquiries: []
    }
  },
  mounted () {
    axios.get(this.api + '/inquiry').then(response => {
      this.inquiries = response.data
    })
  },
  methods: {
    deleteById (id) {
      axios.delete(this.api + '/inquiry/' + id).then(() => {
        axios.get(this.api + '/inquiry').then(response => {
          this.inquiries = response.data
        })
      })
    }
  }
}
</script>

<style scoped>
</style>

// front-react/src/components/ShowAll.js
import React from 'react';
import Layout from "./Layout";
import {Link} from "react-router-dom";
import axios from 'axios'

class ShowAll extends React.Component {
    constructor (props) {
        super(props);
        this.state = {
            inquiries: []
        }
        this.componentDidMount = this.componentDidMount.bind(this)
        this.delete = this.delete.bind(this)
    }

    componentDidMount () {
        axios.get(global.api + '/inquiry').then(response => {
            this.setState({
                inquiries: response.data
            })
        })
    }

    delete (id) {
        axios.delete(global.api + '/inquiry/' + id).then(() => {
            axios.get(global.api + '/inquiry').then(response => {
                this.setState({
                    inquiries: response.data
                })
            })
        })
    }

    render () {
        return (
            <Layout>
                <div className="container">
                    <div className="row justify-content-center">
                        <div className="col-md-8">
                            <div className="card">
                                <div className="card-header">一覧</div>
                                <div className="card-body">
                                    <table className="table">
                                        <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>名前</th>
                                            <th>メール</th>
                                            <th>メッセージ</th>
                                            <th/>
                                            <th/>
                                            <th/>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {this.state.inquiries.map((inquiry) => {
                                            return (
                                                <tr key={inquiry.id}>
                                                    <td>{inquiry.id}</td>
                                                    <td>{inquiry.name}</td>
                                                    <td>{inquiry.mail}</td>
                                                    <td>{inquiry.message}</td>
                                                    <td>
                                                        <Link to={/detail/ + inquiry.id} className="btn btn-primary"
                                                              role="button">詳細
                                                        </Link>
                                                    </td>
                                                    <td>
                                                        <Link to={/edit/ + inquiry.id} className="btn btn-secondary"
                                                              role="button">編集
                                                        </Link>
                                                    </td>
                                                    <td>
                                                        <button className="btn btn-danger"
                                                                onClick={() => this.delete(inquiry.id)}>削除
                                                        </button>
                                                    </td>
                                                </tr>
                                            )
                                        })}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </Layout>
        )
    }
}

export default ShowAll
